spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_ang
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: USER-SERVICE
server:
  port: 2221
eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/










